version: "3.6"
services:
  webserver:
    build:
      context: ./webserver
    volumes:
      - "staticData:/cml/staticData/"
      - "highscoreData:/cml/highscoreData"
    environment:
      RIOT_API_KEY:
      DATA_DIR: "/cml/highscoreData/"
    restart: unless-stopped
volumes:
  staticData:
  highscoreData:
