apiVersion: 1

datasources:
  - name: "Prometheus"
    orgId: 1
    version: 1
    type: prometheus
    url: "http://prometheus:9090"
    access: proxy
    jsonData:
      timeInterval: 30s
    editable: false
    isDefault: true
